version:  '3'
services:
  web:
    build:
      context:  . #current directory contains react project
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    build:
      context:  . #current directory contains react project
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command:  ["npm", "run", "test"]  #overide default command npm run start
    